services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.dockerfile
            args:
                - NGINX_HOST=${NGINX_HOST}
        image: nginx
        ports: 
            - 80:80
        links:
            - fpm
        volumes: 
            - ./app:/var/www/${NGINX_HOST}

    fpm:
        build:
            context: ./
            dockerfile: docker/fpm.dockerfile
            args:
                - NGINX_HOST=${NGINX_HOST}
        volumes: 
            - ./app:/var/www/${NGINX_HOST}
    mysql:
        image: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${PROJ_NAME}
        volumes:
            - ./docker/sqldatadir:/var/lib/mysql